---
user_name: leonardo

- host: localhost
  connection: local
  become: true
  
  tasks:
  - name: install packages
    package: 
      name: 
        - htop
        - tmux
        # to allow dconf to function
        - python3-psutil
        
  - name: copy wallpaper file
    copy:
      src: files/wallpaper.png
      dest: /usr/share/backgrounds/ansible-wallpaper.png
      owner: root
      group: root
      
  - name: set wallpaper
    become_user: {{ user_name }}
    dconf: 
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"
  
  - name: set wallpaper position
    become_user: {{ user_name }}
    dconf: 
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"
      
  - name: copy .bashrc file
    copy:
      src: files/bashrc
      dest: /home/{{user_name}}/.bashrc
      owner: {{user_name}}
      group: {{user_name}}
      
## In case we want to automate an ansible user which checks periodically 
## id there are changes in the repository and executes the playbook       
#  - name: add ansible user
#    user:
#      name: velociraptor
#      system: yes
#
#  - name: set up sudo for ansible user
#    copy:
#      src: files/sudoer_velociraptor
#      dest: /etc/sudoers.d/velociraptor
#      owner: root
#      group: root
#      mode: 0440
#
#  - name: add ansible-pull cron job
#    cron:
#      name: ansible auto-provision
#      user: velociraptor
#      minute: "*/10"
#      job: ansible-pull -o -U [REPLACE WITH URL]
